// Generated by LiveScript 1.3.1
var body, template, ractive, setImmediate, clearImmediate, textarea, shouldSync;
body = document.body;
template = document.getElementById('main').innerHTML;
ractive = new Ractive({
  el: '#main',
  template: template,
  data: (doc.showEditor = false, doc),
  he: function(){
    return this.set('showEditor', false);
  },
  se: function(){
    return this.set('showEditor', true);
  }
});
ractive.on('save', function(){
  return superagent.put(location.pathname).send({
    content: doc.content
  }).end(function(r){
    alert('保存成功');
    return location.hash = '';
  });
});
ractive.observe('content', function(newValue){
  return ractive.set('html', marked(newValue));
});
setImmediate = window.setImmediate || function(){
  var args;
  args = [].slice.call(arguments);
  args.splice(1, 0, 1);
  return setTimeout.apply(this, args);
};
clearImmediate = window.clearImmediate || window.clearTimeout;
textarea = document.querySelector('#editor textarea');
shouldSync = true;
function syncScrollTop(triggerFromBody){
  var timer;
  timer = null;
  return function(ev){
    ev.stopPropagation();
    if (timer || !shouldSync) {
      return;
    }
    shouldSync = false;
    timer = setTimeout(doSync, 100);
    function doSync(){
      _syncScrollTop(triggerFromBody);
      return timer = null;
    }
    return doSync;
  };
}
function _syncScrollTop(triggerFromBody){
  var bst, bsh, tst, tsh, br, st, tr;
  bst = body.scrollTop;
  bsh = body.scrollHeight;
  tst = textarea.scrollTop;
  tsh = textarea.scrollHeight;
  if (triggerFromBody) {
    br = bst / bsh;
    st = Math.floor(tsh * br);
    shouldSync = false;
    textarea.scrollTop = st;
    return setImmediate(function(){
      return shouldSync = true;
    });
  } else {
    tr = tst / tsh;
    st = Math.floor(bsh * tr);
    shouldSync = false;
    body.scrollTop = st;
    return setImmediate(function(){
      return shouldSync = true;
    });
  }
}
window.addEventListener('scroll', syncScrollTop(true), false);
textarea.addEventListener('scroll', syncScrollTop(false), false);
window.addEventListener('hashchange', function(ev){
  if (location.hash === '#edit') {
    return body.classList.add('edit-enable');
  } else {
    return body.classList.remove('edit-enable');
  }
}, false);
window.addEventListener('load', function(ev){
  if (location.hash === '#edit') {
    return location.hash = '';
  }
}, false);